Repository suleymaneser/shopping, pull requests merged in 2021-01, with the labels that each got.

#2 added new features for product
  src/main/java/com/shopping/shopping/domain/Category.java
  src/main/java/com/shopping/shopping/domain/Product.java
  src/main/java/com/shopping/shopping/domain/ProductPrice.java
  src/main/java/com/shopping/shopping/dto/ProductDTO.java
  src/main/java/com/shopping/shopping/repository/CategoryRepository.java
  src/main/java/com/shopping/shopping/repository/ProductPriceRepository.java
  src/main/java/com/shopping/shopping/service/impl/ProductCommandServiceImpl.java
  src/main/java/com/shopping/shopping/service/impl/ShoppingCartCommandServiceImpl.java
  src/test/java/com/shopping/shopping/controller/ProductApiControllerTest.java
Labels: enhancement

#3 waiting for fix run and build error
  src/main/java/com/shopping/shopping/domain/Product.java
  src/main/java/com/shopping/shopping/domain/ProductPrice.java
  src/main/java/com/shopping/shopping/dto/ProductDTO.java
  src/main/java/com/shopping/shopping/enums/CurrencyType.java
  src/main/java/com/shopping/shopping/service/ProductQueryService.java
  src/main/java/com/shopping/shopping/service/impl/ProductCommandServiceImpl.java
  src/main/java/com/shopping/shopping/service/impl/ProductQueryServiceImpl.java
  src/main/java/com/shopping/shopping/startup/ProductDemoData.java
  ui/README.md
Labels: bug

#4 fixed error when build project
  src/main/java/com/shopping/shopping/startup/ProductDemoData.java
  src/main/resources/application.properties
Labels: bug

#5 new arrangments
  src/main/java/com/shopping/shopping/controller/ProductApiController.java
  src/main/java/com/shopping/shopping/domain/Product.java
  src/main/java/com/shopping/shopping/domain/ProductPrice.java
  src/main/java/com/shopping/shopping/dto/ProductDTO.java
  src/main/java/com/shopping/shopping/dto/request/UpdateProductRequest.java
  src/main/java/com/shopping/shopping/repository/ProductRepository.java
  src/main/java/com/shopping/shopping/service/ProductCommandService.java
  src/main/java/com/shopping/shopping/service/ProductQueryService.java
  src/main/java/com/shopping/shopping/service/impl/ProductCommandServiceImpl.java
  src/main/java/com/shopping/shopping/service/impl/ProductQueryServiceImpl.java
  src/main/java/com/shopping/shopping/startup/ProductDemoData.java
  src/main/resources/application.properties
  src/test/java/com/shopping/shopping/controller/ProductApiControllerTest.java
Labels: enhancement

#6 shopping 1
  src/main/java/com/shopping/shopping/controller/ProductApiController.java
  src/main/java/com/shopping/shopping/domain/Category.java
  src/main/java/com/shopping/shopping/domain/Customer.java
  src/main/java/com/shopping/shopping/domain/ProductPrice.java
  src/main/java/com/shopping/shopping/dto/CustomerDTO.java
  src/main/java/com/shopping/shopping/dto/ProductDTO.java
  src/main/java/com/shopping/shopping/dto/ProductPriceDTO.java
  src/main/java/com/shopping/shopping/repository/CategoryRepository.java
  src/main/java/com/shopping/shopping/service/ProductCommandService.java
  src/main/java/com/shopping/shopping/service/impl/ProductCommandServiceImpl.java
  src/main/java/com/shopping/shopping/startup/ProductDemoData.java
  src/test/java/com/shopping/shopping/controller/ProductApiControllerTest.java
Labels: enhancement

#7 jenkins job example
  src/main/resources/application.properties
Labels: enhancement

#8 jenkins job example 2
  src/main/resources/application.properties
Labels: enhancement

#9 ui example
  src/main/java/com/shopping/shopping/domain/Category.java
  ui/package-lock.json
  ui/package.json
  ui/src/common/config.js
  ui/src/components/Product.vue
  ui/src/main.js
Labels: enhancement

#16 Update | added User Information of gitlab
  README.md
Labels: documentation

#17 added create api for customer type
  src/main/java/com/shopping/shopping/controller/CustomerTypeApiController.java
  src/main/java/com/shopping/shopping/controller/ProductApiController.java
  src/main/java/com/shopping/shopping/domain/CustomerType.java
  src/main/java/com/shopping/shopping/dto/CustomerTypeDTO.java
  src/main/java/com/shopping/shopping/dto/response/CustomerTypeResponse.java
  src/main/java/com/shopping/shopping/service/CustomerTypeCommandService.java
  src/main/java/com/shopping/shopping/service/impl/CustomerTypeCommandServiceImpl.java
Labels: enhancement

#18 fixed ui error
  pom.xml
  src/main/java/com/shopping/shopping/controller/ProductApiController.java
  ui/package.json
  ui/src/components/Product.vue
  ui/src/main.js
Labels: bug

#19 added images
  src/main/java/com/shopping/shopping/domain/Product.java
  src/main/java/com/shopping/shopping/dto/ProductDTO.java
  src/main/java/com/shopping/shopping/service/impl/ProductCommandServiceImpl.java
  ui/src/components/Product.vue
Labels: enhancement

#25 added new screen
  ui/package-lock.json
  ui/package.json
  ui/src/App.vue
  ui/src/assets/market.jpg
  ui/src/assets/product.jpg
  ui/src/common/customer.service.js
  ui/src/common/product.service.js
  ui/src/components/CustomerListComponent.vue
  ui/src/components/HomeDetailComponent.vue
  ui/src/components/ProductListComponent.vue
  ui/src/main.js
  ui/src/router/index.js
  ui/src/views/About.vue
  ui/src/views/Customer.vue
  ui/src/views/Home.vue
  ui/src/views/Product.vue
Labels: enhancement

#27 fix
  ui/src/components/CustomerListComponent.vue
  ui/src/components/HomeDetailComponent.vue
Labels: bug
